version: '3'

volumes:
  trust-volume:

services:
  trust:
    image: alpine
    command: sh -c "
        wget \"http://repository.egi.eu/sw/production/cas/1/current/tgz/\" &&
        mkdir tgz && mkdir certificates &&
        for tgz in $$(cat index.html | awk -F'\"' '{print $$8}' | grep tar.gz);
        do wget http://repository.egi.eu/sw/production/cas/1/current/tgz/$$tgz -O tgz/$$tgz;
        done && for tgz in $$(ls tgz/);
        do tar xzf tgz/$$tgz --strip-components=1 -C certificates/; done &&
        for f in $$(find certificates/ -type f -name \"*.pem\");
        do cat $$f >> /certs/ca-certificates.crt; done &&
        nc -l -p 8085
      "
    volumes:
      - trust-volume:/certs

  webdav:
    image: ffornari/apache-openidc-oauth-webdav
    restart: always
    ports:
      - "8080:80"
    extra_hosts:
      - "${IAM_HOST}:${IAM_IP}"
    links:
      - "trust:trust"
    environment:
      IAM_HOST: ${IAM_HOST}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    volumes:
      - /opt/apache-webdav:/var/lib/dav
      - trust-volume:/etc/ssl/certs
    depends_on:
      - trust
